import imagen from "./Imágenes/Banner_sin-degradado.png"

export const alimentos = [
        {
            nombre: "Pepas",
            precio: 3000,
            img: {imagen},
            ingredientes: "Harina de trigo, Aceite de girasol, Azúcar, Huevo, Dulce de membrillo, Polvo de hornear",
            info: "Disfrutá de las mejores pepas de San Vicente, hechas totalmente a mano y con mucho amor!",
            versiones: ["Membrillo", "Batata", "Dulce de Leche"],
            celiaco: false,
            vegano: false,
        },
        {
            nombre: "Pan Integral",
            precio: 5000,
            img: {imagen},
            ingredientes: "Harina de trigo integral, Agua, Levadura, Sal, Azúcar ",
            info: "Disfrutá del mejor pan integral de San Vicente, hecho totalmente a mano y con mucho amor!",
            versiones: ["con semilas, Sin semillas"],
            celiaco: false,
            vegano: true,
        },
        {
            nombre: "Pan Blanco",
            precio: 3000,
            img: {imagen},
            ingredientes: "Harina de trigo, Agua, Levadura, Sal, Azúcar",
            info: "Disfrutá del mejor pan blanco de San Vicente, hecho totalmente a mano y con mucho amor!",
            versiones: ["Con semillas", "Sin semillas"],
            celiaco: false,
            vegano: true,
        },
        {
            nombre: "Pan masa madre",
            precio: 5000,
            img: {imagen},
            ingredientes: "Harina de trigo, Agua, Sal",
            info: "Disfrutá del mejor pan de masa madre de San Vicente, hecho totalmente a mano y con mucho amor!",
            versiones: ["Con semillas", "Sin semillas"],
            celiaco: false,
            vegano: true,
        },
        {
            nombre: "Budín de Vainilla",
            precio: 3000,
            img: {imagen},
            ingredientes: "Harina de trigo, Huevo, Azúcar, Aceite de girasol, Esencia de vainilla, polvo de hornear",
            info: "Disfrutá del mejor budín de San Vicente, hecho totalmente a mano y con mucho amor!",
            versiones: ["Con glaseado", "Sin glaseado"],
            celiaco: false,
            vegano: false,
        },
        {
            nombre: "Budín de Chocolate",
            precio: 3000,
            img: {imagen},
            ingredientes: "Harina de trigo, Huevo, Azúcar, Aceite de girasol, Cacao amargo en polvo, polvo de hornear",
            info: "Disfrutá del mejor budín de San Vicente, hecho totalmente a mano y con mucho amor!",
            versiones: ["Normal"],
            celiaco: false,
            vegano: false,
          
        },
        {
            nombre: "Budín de Limón",
            precio: 3000,
            img: {imagen},
            ingredientes: "Harina de trigo, Huevo, Azúcar, Aceite de girasol, Ralladura de limón, polvo de hornear",
            info: "Disfrutá del mejor budín de San Vicente, hecho totalmente a mano y con mucho amor!",
            versiones: ["Con glaseado", "Sin glaseado"],
            celiaco: false,
            vegano: false,
        },
        {
            nombre: "Berlinesas",
            precio: 4000,
            img: {imagen},
            ingredientes: "Harina de trigo, Agua, Huevo, Manteca, Azúcar, Esencia de vainilla",
            info: "Disfrutá de las mejores berlinesas de San Vicente, hechas totalmente a mano y con mucho amor!",
            versiones: ["Con glaseado", "Sin glaseado"],
            celiaco: false,
            vegano: false,

        },
        {
            nombre: "Facturas",
            precio: 5000,
            img: {imagen},
            ingredientes: "Harina de trigo, Agua, Huevo, Manteca, Azúcar, Esencia de vainilla",
            info: "Disfrutá de las mejores facturas de San Vicente, hechas totalmente a mano y con mucho amor!",
            versiones: ["Con pastelera", "Con dulce de leche, Medialunas de grasa, Medialunas de manteca"],
            celiaco: false,
            vegano: false,
            
        },
        {
            nombre: "Facturas sin gluten",
            precio: 5000,
            img: {imagen},
            ingredientes: "Premezcla sin gluten, Agua, Huevo, Manteca, Azúcar, Esencia de vainilla",
            info: "Disfrutá de las mejores facturas sin gluten de San Vicente, hechas totalmente a mano y con mucho amor!",
            versiones: ["Con pastelera", "Con dulce de leche, Medialunas de grasa, Medialunas de manteca"],
            celiaco: true,
            vegano: false,
        },
        {
            nombre: "Budín de vainilla sin gluten",
            precio: 3000,
            img: {imagen},
            ingredientes: "Premezcla sin gluten, Huevo, Azúcar, Aceite de girasol, Ralladura de limón, polvo de hornear",
            info: "Disfrutá del mejor budín de San Vicente, hecho totalmente a mano y con mucho amor!",
            versiones: ["Con glaseado", "Sin glaseado"],
            celiaco: true,
            vegano: false,
        },
        {
            nombre: "Budín de Chocolate sin gluten",
            precio: 3000,
            img: {imagen},
            ingredientes: "Premezcla sin gluten, Huevo, Azúcar, Aceite de girasol, Ralladura de limón, polvo de hornear",
            info: "Disfrutá del mejor budín de San Vicente, hecho totalmente a mano y con mucho amor!",
            versiones: ["Normal"],
            celiaco: true,
            vegano: false,
        },
        
    ]